name: Go

defaults:
  run:
    shell: bash --noprofile --norc -eo pipefail {0}

on:
  push:
    branches: [master, main, force_test, release-*, staging, trying]
  pull_request:
    branches: ['**']

env:
  golang-version: 1.17.7
  golangci-lint-version: v1.44.2

jobs:
  build:
    name: Build and Lint
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Set up Go ${{ env.golang-version }}
      uses: actions/setup-go@v3.0.0
      with:
        go-version: ${{ env.golang-version }}
      id: go

    - name: Lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: ${{ env.golangci-lint-version }}

    - name: Format
      run: |
        make go-fmt
        git diff --exit-code .

    - name: Build
      run: make build

  test:
    name: unit
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Checkout test data files
      run: wget https://github.com/timescale/promscale-test-data/raw/main/traces-dataset.sz -O pkg/tests/testdata/traces-dataset.sz

    - name: Set up Go ${{ env.golang-version }}
      uses: actions/setup-go@v3.0.0
      with:
        go-version: ${{ env.golang-version }}
      id: go

    - name: Use Go module caching
      uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Test
      run: make test > complete-test-run.log  2>&1

    - name: 'Print failure logs'
      if: ${{ failure() }}
      run: grep "^[- F]" complete-test-run.log

    - name: 'Upload Log Artifact'
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: complete-test-run.log
        path: complete-test-run.log
        retention-days: 5

    - name: Generated
      run: |
        go generate ./...
        git diff --exit-code

  test-end-to-end:
    name: e2e
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test-setups:
        - {name: "Singlenode (12)",          shortname: "singlenode-12",  tsdb: true,  multi: false, pg: 12}
        - {name: "Singlenode (13)",          shortname: "singlenode-13",  tsdb: true,  multi: false, pg: 13}
        - {name: "Singlenode",               shortname: "singlenode-14",  tsdb: true,  multi: false, pg: 14}
        - {name: "Without TimescaleDB",      shortname: "no-timescaledb", tsdb: false, multi: false, pg: 14}
        - {name: "Multinode",                shortname: "multinode",      tsdb: true,  multi: true,  pg: 14}

    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - name: Checkout test data files
      run: wget https://github.com/timescale/promscale-test-data/raw/main/traces-dataset.sz -O pkg/tests/testdata/traces-dataset.sz

    - name: Set up Go ${{ env.golang-version }}
      uses: actions/setup-go@v3.0.0
      with:
        go-version: ${{ env.golang-version }}
      id: go

    - name: Use Go module caching
      uses: actions/cache@v2
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Test ${{ matrix.test-setups.name }}
      env:
        PG: ${{ matrix.test-setups.pg }}
        TSDB: ${{ matrix.test-setups.tsdb }}
        MULTI: ${{ matrix.test-setups.multi }}
        SHORTNAME: ${{ matrix.test-setups.shortname }}
      run: go test -race -timeout=30m ./pkg/tests/end_to_end_tests/ -use-timescaledb=$TSDB -use-multinode=$MULTI -postgres-version-major=$PG -promscale-extension-version=jg-ha-dockerfile | tee $SHORTNAME-test-run.log  2>&1

    - name: 'Upload Log Artifact'
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.test-setups.shortname }}-test-run.log
        path: ${{ matrix.test-setups.shortname }}-test-run.log
        retention-days: 5

  # Added to summarize the matrix (otherwise we would need to list every single
  # job in bors.toml)
  tests-result:
    name: e2e results
    if: always()
    needs:
      - test-end-to-end
    runs-on: ubuntu-latest
    steps:
      - name: Mark the job as a success
        if: needs.test-end-to-end.result == 'success'
        run: exit 0
      - name: Mark the job as a failure
        if: needs.test-end-to-end.result != 'success'
        run: exit 1
